// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ButtonModuleCss from "./Button.module.css";

var styles = ButtonModuleCss;

function Button(Props) {
  return React.createElement("button", {
              className: styles.button
            }, "hey");
}

var make = Button;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
