// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./components/Button.bs.js";
import * as Sidebar from "./components/Sidebar.bs.js";
import AppModuleCss from "./App.module.css";

var styles = AppModuleCss;

function App(Props) {
  return React.createElement("div", {
              className: styles.container
            }, React.createElement("div", {
                  className: styles.column
                }, React.createElement(Button.make, {}), React.createElement(Button.make, {})), React.createElement(Sidebar.make, {}));
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
